---
- name: Check if Docker is installed
  hosts: 35.154.25.107
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install Docker if not installed
      apt:
        name: docker.io
        state: present
      when: docker_check.rc != 0

- name: Pull Docker Image From DockerHub
  hosts: 35.154.25.107
  remote_user: ubuntu
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "karnadevsinh9/calcsci:{{DOCKER_TAG}}"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Request
      debug:
        var: docker_pull_result

    - name: Running Container
      docker_container:
        name: calculator
        image: karnadevsinh9/calcsci:{{DOCKER_TAG}}
        tty: yes
        interactive: yes
        command: /bin/bash

