---
- name: Check if Docker is installed
  hosts: 35.154.25.107
  become: true
  tasks:
    - name: Check if Docker is installed
      command: docker --version
      ignore_errors: true
      register: docker_check

    - name: Install prerequisites for Docker (Ubuntu)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present
      when: docker_check.rc != 0
      become: true
      become_user: root

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      when: docker_check.rc != 0
      become: true
      become_user: root

    - name: Add Docker's official repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present
      when: docker_check.rc != 0
      become: true
      become_user: root

    - name: Install Docker
      apt:
        name: docker-ce
        state: present
      when: docker_check.rc != 0
      become: true
      become_user: root


- name: Pull Docker Image From DockerHub
  hosts: 35.154.25.107
  remote_user: ubuntu
  become: false
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "karnadevsinh9/calcsci:{{DOCKER_TAG}}"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Request
      debug:
        var: docker_pull_result

    - name: Running Container
      docker_container:
        name: calculator
        image: karnadevsinh9/calcsci:{{DOCKER_TAG}}
        tty: true
        interactive: true
        command: /bin/bash

